---
- hosts: all
  gather_facts: yes
  tasks:
    - name: ping
      command: "ping -c 1 {{ hostvars[item].vxlan_ip }} -w 1"
      with_items: "{{ groups['all'] }}"
      when:
        - hostvars[item].vxlan_ip is defined
        - item != inventory_hostname
      changed_when: false
