---
- hosts: all
  gather_facts: yes
  tasks:
    - name: clean file
      shell: "echo 'ip link delete {{vxlan_interface}}'> /vxlan_config"
      when: inventory_hostname == item
      with_items: "{{ groups['all'] }}"
    - name: create vxlan interface
      shell: "echo 'ip link add {{vxlan_interface}} type vxlan id 16 local {{ hostvars[item].wireguard_ip}} dev wg0 dstport 4789' >> /vxlan_config"
      when: inventory_hostname == item
      with_items: "{{ groups['all'] }}"
    - name: generate Preshared keyskeypair
      shell: "echo 'bridge fdb append 00:00:00:00:00:00 dev {{vxlan_interface}} dst {{ hostvars[item].wireguard_ip}}' >> /vxlan_config"
      with_items: "{{ groups['all'] }}"
      when: item != inventory_hostname
    - name: create vxlan interface
      shell: "echo 'ip addr add {{ hostvars[item].vxlan_ip}}/{{vxlan_mask_bits}} dev {{vxlan_interface}}' >> /vxlan_config"
      when: inventory_hostname == item
      with_items: "{{ groups['all'] }}"
    - name: create vxlan interface
      shell: "echo 'ip link set up dev {{vxlan_interface}}' >> /vxlan_config"
      when: inventory_hostname == item
      with_items: "{{ groups['all'] }}"
### example of a file it will create
# ip link delete vx0
# ip link add vx0 type vxlan id 16 local 10.99.10.254 dev wg0 dstport 4789
# bridge fdb append 00:00:00:00:00:00 dev vx0 dst 10.99.10.11
# bridge fdb append 00:00:00:00:00:00 dev vx0 dst 10.99.10.12
# bridge fdb append 00:00:00:00:00:00 dev vx0 dst 10.99.10.13
# bridge fdb append 00:00:00:00:00:00 dev vx0 dst 10.99.10.51
# ip addr add 10.129.16.254/24 dev vx0
# ip link set up dev vx0 dev vx0
