---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Setup vxlan interface
      template:
        src: ./templates/vxlan.network
        dest: /etc/systemd/network/100-vx0.network
        owner: root
        group: systemd-network
        mode: 0640
      become: yes
      notify: systemd network restart
      when: vxlan_ip is defined and vxlan_ip
    - name: Setup vxlan nedev
      template:
        src: ./templates/vxlan.netdev
        dest: /etc/systemd/network/100-vx0.netdev
        owner: root
        group: systemd-network
        mode: 0640
      become: yes
      notify: systemd network restart
      when: vxlan_ip is defined and vxlan_ip
  handlers:
    - name: systemd network restart
      service:
        name: systemd-networkd
        state: restarted
        enabled: yes
      become: yes
